### ISSUE TITLE
Canonicalize YAML mapping order

### ISSUE THREAD

**Issue by dlecocq** [outlyerapp/dlcli#4]
We commit our exported dashboards to source control. Yesterday I exported one of my dashboards and today I `pull`ed it again and it appeared that some of the keys had been reordered. Here's a snippet from the `diff`:

```
@@ -28,25 +28,25 @@ positions:
     col: 4
     size_x: 3
     size_y: 3
-    filter: avg
-    legend: false
     icon: true
+    legend: false
+    filter: avg
     series:
```

Is it possible to canonicalize the order of mapping keys?

**Comment by sacreman** [comment]
This looks like an API bug.YAML is unordered usually but internally we agreed to set an order so that dashboards could be exported and imported and remain identical. Paging @ThibaultLaurens to have a look in the API.

**Comment by dlecocq** [comment]
Right. Unlike `simplejson`, `pyyaml` (assuming what you're using behind the scenes) doesn't appear to have a `sort_keys` option when `dump`-ing.

From the client code, `pull` seems to just straight up `print` the `content` returned from the API -- this just seemed like a convenient venue for drawing attention to the issue.

Figured I'd mention because I imagine others have a similar use-case. Thanks for looking into it!

**Comment by thibaultlaurens** [comment]
Hi @dlecocq thanks for reporting I just checked and can see the issue, I will push a fix tomorrow.

**Comment by thibaultlaurens** [comment]
@dlecocq just pushed to prod, here is the definite order for positions keys:

```
positions:
  - title:
    data_type:
    type:
    color:
    icon:
    symbol:
    filter:
    legend: 
    row:
    col:
    size_x:
    size_y:
    series:
```

**Comment by dlecocq** [comment]
Thank you kindly!
