### ISSUE TITLE
No feedback when pushing dashboards.

### ISSUE THREAD

**Issue by DevOpsDave** [outlyerapp/dlcli#9]
When trying to update dashboards, the user gets 0 feedback if the operation was successful or not.  
While working on dashboards, I accidentally introduced some bad formatting in my yaml.  For a bit I thought there was something wrong with the dataloop service because none of my changes were showing up on the website.  

To illustrate this issue, if one creates an empty yaml file, the output of dlcli is the same as pushing a valid yaml file.

```
~/D/c/g/assistly ❯❯❯ touch blah.yaml
~/D/c/g/assistly ❯❯❯ dlcli push dashboard blah.yaml
~/D/c/g/assistly ❯❯❯ echo $?
0
```

**Comment by sacreman** [comment]
I've added more error handling around the push commands. I'm not sure that solves this issue however, as I get the following when pulling an empty pushed file. Pushing an empty file is like creating a dashboard with no content in it yet (which is valid).

`Steven-MacPro:~ sacreman$ ~/dlcli/run_dlcli.py pull dashboard microservice2`

```
title: microservice2
annotations: []
period: 600
locked: false
positions: []
```

I could check for 0 byte files in dlcli and throw an error. The API should return a non 200 status code for invalid yaml. I'm not sure it currently does. I'll ask @ThibaultLaurens to see if we can validate this better.

**Comment by DevOpsDave** [comment]
I think one of the issues is you don't get any feedback if memory serves.
Maybe if you get the status code and the number of bytes uploaded would be
helpful. Then don't have to change the behavior of pushing empty
dashboards. Just put the onus back on the user to watch for the feedback
and decide if it was successful or not.

**Comment by sacreman** [comment]
I've updated it to print the content length as part of the output (on success and error).

```
Pushed dashboard: /Users/sacreman/private_packs/microservice1/dashboards/microservice2.yaml Content Length: 16
Steven-MacPro:dlcli sacreman$ ~/dlcli/run_dlcli.py push dashboard ~/private_packs/microservice1/dashboards/microservice1.yaml
Pushed dashboard: /Users/sacreman/private_packs/microservice1/dashboards/microservice1.yaml Content Length: 354
```
